//Firework Ignition System rev 2
//Written by: Hyrum Powell
//Date: JUNE 23th 2024

//Assigning variables to Digital IO pins
int D2;
int D3;
int Start;
int DIP2 = 2;
int DIP3 = 3;
int StartButton = 4;
int ProgLED1 = 11;
int ProgLED2 = 10;
int ProgLED3 = 9;
int ProgLED4 = 8;
int ButtonLED = 12;
int Ign1 = 22;
int Ign2 = 24;
int Ign3 = 26;
int Ign4 = 28;
int Ign5 = 30;
int Ign6 = 32;
int Ign7 = 34;
int Ign8 = 36;
int Ign9 = 38;
int Ign10 = 40;
int Ign11 = 42;
int Ign12 = 44;
int Ign13 = 46;
int Ign14 = 48;
int Ign15 = 50;
int Ign16 = 52;

//Time delay variables
int Pause = 6000;
int IgnTime = 5000;

void setup() {
pinMode(DIP2,INPUT_PULLUP);
pinMode(DIP3,INPUT_PULLUP);
pinMode(StartButton,INPUT_PULLUP);
pinMode(ProgLED1,OUTPUT);
pinMode(ProgLED2,OUTPUT);
pinMode(ProgLED3,OUTPUT);
pinMode(ProgLED4,OUTPUT);
pinMode(ButtonLED,OUTPUT);  
pinMode(Ign1,OUTPUT);
pinMode(Ign2,OUTPUT);
pinMode(Ign3,OUTPUT);
pinMode(Ign4,OUTPUT);
pinMode(Ign5,OUTPUT);
pinMode(Ign6,OUTPUT);
pinMode(Ign7,OUTPUT);
pinMode(Ign8,OUTPUT);
pinMode(Ign9,OUTPUT);
pinMode(Ign10,OUTPUT);
pinMode(Ign11,OUTPUT);
pinMode(Ign12,OUTPUT);
pinMode(Ign13,OUTPUT);
pinMode(Ign14,OUTPUT);
pinMode(Ign15,OUTPUT);
pinMode(Ign16,OUTPUT);
Serial.begin(9600);
}

void loop() {
// High values turn the relay off, and Low turns it on
D2=digitalRead(DIP2);
D3=digitalRead(DIP3);
Start=digitalRead(StartButton);
digitalWrite(Ign1,HIGH);
digitalWrite(Ign2,HIGH);
digitalWrite(Ign3,HIGH);
digitalWrite(Ign4,HIGH);
digitalWrite(Ign5,HIGH);
digitalWrite(Ign6,HIGH);
digitalWrite(Ign7,HIGH);
digitalWrite(Ign8,HIGH);
digitalWrite(Ign9,HIGH);
digitalWrite(Ign10,HIGH);
digitalWrite(Ign11,HIGH);
digitalWrite(Ign12,HIGH);
digitalWrite(Ign13,HIGH);
digitalWrite(Ign14,HIGH);
digitalWrite(Ign15,HIGH);
digitalWrite(Ign16,HIGH);

// For debugging Button presses
//Serial.print(" DIP2 ");
//Serial.println(D2);
//Serial.print(" DIP3 ");
//Serial.println(D3);
//Serial.print(" Start ");
//Serial.println(Start);
//delay(2000);

//Program 1 Sequential Singles for Shells and Canisters 1-16
if(D2==1&&D3==1&&Start==0){
digitalWrite(ProgLED1,HIGH);
digitalWrite(Ign1,HIGH);
digitalWrite(Ign2,HIGH);
digitalWrite(Ign3,HIGH);
digitalWrite(Ign4,HIGH);
digitalWrite(Ign5,HIGH);
digitalWrite(Ign6,HIGH);
digitalWrite(Ign7,HIGH);
digitalWrite(Ign8,HIGH);
digitalWrite(Ign9,HIGH);
digitalWrite(Ign10,HIGH);
digitalWrite(Ign11,HIGH);
digitalWrite(Ign12,HIGH);
digitalWrite(Ign13,HIGH);
digitalWrite(Ign14,HIGH);
digitalWrite(Ign15,HIGH);
digitalWrite(Ign16,HIGH);
delay(Pause);
digitalWrite(Ign1,LOW);
delay(IgnTime);
digitalWrite(Ign1,HIGH);
delay(Pause);
digitalWrite(Ign2,LOW);
delay(IgnTime);
digitalWrite(Ign2,HIGH);
delay(Pause);
digitalWrite(Ign3,LOW);
delay(IgnTime);
digitalWrite(Ign3,HIGH);
delay(Pause);
digitalWrite(Ign4,LOW);
delay(IgnTime);
digitalWrite(Ign4,HIGH);
delay(Pause);
digitalWrite(Ign5,LOW);
delay(IgnTime);
digitalWrite(Ign5,HIGH);
delay(Pause);
digitalWrite(Ign6,LOW);
delay(IgnTime);
digitalWrite(Ign6,HIGH);
delay(Pause);
digitalWrite(Ign7,LOW);
delay(IgnTime);
digitalWrite(Ign7,HIGH);
delay(Pause);
digitalWrite(Ign8,LOW);
delay(IgnTime);
digitalWrite(Ign8,HIGH);
delay(Pause);
digitalWrite(Ign9,LOW);
delay(IgnTime);
digitalWrite(Ign9,HIGH);
delay(Pause);
digitalWrite(Ign10,LOW);
delay(IgnTime);
digitalWrite(Ign10,HIGH);
delay(Pause);
digitalWrite(Ign11,LOW);
delay(IgnTime);
digitalWrite(Ign11,HIGH);
delay(Pause);
digitalWrite(Ign12,LOW);
delay(IgnTime);
digitalWrite(Ign12,HIGH);
delay(Pause);
digitalWrite(Ign13,LOW);
delay(IgnTime);
digitalWrite(Ign13,HIGH);
delay(Pause);
digitalWrite(Ign14,LOW);
delay(IgnTime);
digitalWrite(Ign14,HIGH);
delay(Pause);
digitalWrite(Ign15,LOW);
delay(IgnTime);
digitalWrite(Ign15,HIGH);
delay(Pause);
digitalWrite(Ign16,LOW);
delay(IgnTime);
digitalWrite(Ign16,HIGH);
delay(Pause);
digitalWrite(ProgLED1,LOW);
}

//Program 2 Sequential Doubles for shells and canisters 1-16
if(D2==0&&D3==1&&Start==0){
digitalWrite(ProgLED1,HIGH);
digitalWrite(ProgLED2,HIGH);
digitalWrite(Ign1,HIGH);
digitalWrite(Ign2,HIGH);
digitalWrite(Ign3,HIGH);
digitalWrite(Ign4,HIGH);
digitalWrite(Ign5,HIGH);
digitalWrite(Ign6,HIGH);
digitalWrite(Ign7,HIGH);
digitalWrite(Ign8,HIGH);
digitalWrite(Ign9,HIGH);
digitalWrite(Ign10,HIGH);
digitalWrite(Ign11,HIGH);
digitalWrite(Ign12,HIGH);
digitalWrite(Ign13,HIGH);
digitalWrite(Ign14,HIGH);
digitalWrite(Ign15,HIGH);
digitalWrite(Ign16,HIGH);
delay(Pause);
digitalWrite(Ign1,LOW);
digitalWrite(Ign2,LOW);
delay(IgnTime);
digitalWrite(Ign1,HIGH);
digitalWrite(Ign2,HIGH);
delay(Pause);
digitalWrite(Ign3,LOW);
digitalWrite(Ign4,LOW);
delay(IgnTime);
digitalWrite(Ign3,HIGH);
digitalWrite(Ign4,HIGH);
delay(Pause);
digitalWrite(Ign5,LOW);
digitalWrite(Ign6,LOW);
delay(IgnTime);
digitalWrite(Ign5,HIGH);
digitalWrite(Ign6,HIGH);
delay(Pause);
digitalWrite(Ign7,LOW);
digitalWrite(Ign8,LOW);
delay(IgnTime);
digitalWrite(Ign7,HIGH);
digitalWrite(Ign8,HIGH);
delay(Pause);
digitalWrite(Ign9,LOW);
digitalWrite(Ign10,LOW);
delay(IgnTime);
digitalWrite(Ign9,HIGH);
digitalWrite(Ign10,HIGH);
delay(Pause);
digitalWrite(Ign11,LOW);
digitalWrite(Ign12,LOW);
delay(IgnTime);
digitalWrite(Ign11,HIGH);
digitalWrite(Ign12,HIGH);
delay(Pause);
digitalWrite(Ign13,LOW);
digitalWrite(Ign14,LOW);
delay(IgnTime);
digitalWrite(Ign13,HIGH);
digitalWrite(Ign14,HIGH);
delay(Pause);
digitalWrite(Ign15,LOW);
digitalWrite(Ign16,LOW);
delay(IgnTime);
digitalWrite(Ign15,HIGH);
digitalWrite(Ign16,HIGH);
delay(Pause);
digitalWrite(ProgLED1,LOW);
digitalWrite(ProgLED2,LOW);
}

//Program 3 Sequential Singles and Doubles for shells and canisters 1-16.
if(D2==0&&D3==0&&Start==0){
digitalWrite(ProgLED1,HIGH);
digitalWrite(ProgLED2,HIGH);
digitalWrite(ProgLED3,HIGH);
digitalWrite(Ign1,HIGH);
digitalWrite(Ign2,HIGH);
digitalWrite(Ign3,HIGH);
digitalWrite(Ign4,HIGH);
digitalWrite(Ign5,HIGH);
digitalWrite(Ign6,HIGH);
digitalWrite(Ign7,HIGH);
digitalWrite(Ign8,HIGH);
digitalWrite(Ign9,HIGH);
digitalWrite(Ign10,HIGH);
digitalWrite(Ign11,HIGH);
digitalWrite(Ign12,HIGH);
digitalWrite(Ign13,HIGH);
digitalWrite(Ign14,HIGH);
digitalWrite(Ign15,HIGH);
digitalWrite(Ign16,HIGH);
delay(Pause);
digitalWrite(Ign1,LOW);
delay(IgnTime);
digitalWrite(Ign1,HIGH);
delay(Pause);
digitalWrite(Ign2,LOW);
delay(IgnTime);
digitalWrite(Ign2,HIGH);
delay(Pause);
digitalWrite(Ign3,LOW);
digitalWrite(Ign4,LOW);
delay(IgnTime);
digitalWrite(Ign3,HIGH);
digitalWrite(Ign4,HIGH);
delay(Pause);
digitalWrite(Ign5,LOW);
delay(IgnTime);
digitalWrite(Ign5,HIGH);
delay(Pause);
digitalWrite(Ign6,LOW);
digitalWrite(Ign7,LOW);
delay(IgnTime);
digitalWrite(Ign6,HIGH);
digitalWrite(Ign7,HIGH);
delay(Pause);
digitalWrite(Ign8,LOW);
delay(IgnTime);
digitalWrite(Ign8,HIGH);
delay(Pause);
digitalWrite(Ign9,LOW);
digitalWrite(Ign10,LOW);
delay(IgnTime);
digitalWrite(Ign9,HIGH);
digitalWrite(Ign10,HIGH);
delay(Pause);
digitalWrite(Ign11,LOW);
delay(IgnTime);
digitalWrite(Ign11,HIGH);
delay(Pause);
digitalWrite(Ign12,LOW);
digitalWrite(Ign13,LOW);
delay(IgnTime);
digitalWrite(Ign12,HIGH);
digitalWrite(Ign13,HIGH);
delay(Pause);
digitalWrite(Ign14,LOW);
delay(IgnTime);
digitalWrite(Ign14,HIGH);
delay(Pause);
digitalWrite(Ign15,LOW);
digitalWrite(Ign16,LOW);
delay(IgnTime);
digitalWrite(Ign15,HIGH);
digitalWrite(Ign16,HIGH);
delay(Pause);
digitalWrite(ProgLED1,LOW);
digitalWrite(ProgLED2,LOW);
digitalWrite(ProgLED3,LOW);
}

//Program 4 Singles when the start button is pushed. Tube 16 only
if(D2==1&&D3==0&&Start==0){
digitalWrite(ProgLED1,HIGH);
digitalWrite(ProgLED2,HIGH);
digitalWrite(ProgLED3,HIGH);
digitalWrite(ProgLED4,HIGH);
digitalWrite(Ign1,HIGH);
digitalWrite(Ign2,HIGH);
digitalWrite(Ign3,HIGH);
digitalWrite(Ign4,HIGH);
digitalWrite(Ign5,HIGH);
digitalWrite(Ign6,HIGH);
digitalWrite(Ign7,HIGH);
digitalWrite(Ign8,HIGH);
digitalWrite(Ign9,HIGH);
digitalWrite(Ign10,HIGH);
digitalWrite(Ign11,HIGH);
digitalWrite(Ign12,HIGH);
digitalWrite(Ign13,HIGH);
digitalWrite(Ign14,HIGH);
digitalWrite(Ign15,HIGH);
digitalWrite(Ign16,HIGH);
delay(Pause);
digitalWrite(Ign16,LOW);
delay(IgnTime);
digitalWrite(Ign16,HIGH);
delay(Pause);
digitalWrite(ProgLED1,LOW);
digitalWrite(ProgLED2,LOW);
digitalWrite(ProgLED3,LOW);
digitalWrite(ProgLED4,LOW);
}

}
